spring:
  application:
    name: TaskManagement
    version: 1.0.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 86400000 

app:
  demo-content:
    enabled: false